
[build]
  publish = "build"    
  command = "npm run build"  

# Redirects Configuration
[[redirects]]
  from = "/api/*"
  to = "https://attendanceappadminportal.onrender.com/api/:splat"
  status = 200
  force = true


